name: Release

on:
    push:
        branches: [ "main" ]
        tags: [ "*" ]
    pull_request:
        branches: [ "main" ]

jobs:
    release:
        # To use old glibc to link
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                target:
                    - "x86_64-unknown-linux-gnu"

        steps:
            -   uses: actions/checkout@v3

            -   name: Install rust
                uses: dtolnay/rust-toolchain@stable

            -   name: Check version
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    [ "v$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].version')" = "$GITHUB_REF_NAME" ]

            -   name: Build
                run: cargo build --release --verbose --target=${{ matrix.target }}

            -   name: Pack artifacts
                run: |
                    mkdir -p dest
                    cp target/${{ matrix.target }}/release/archivedon-fetch dest/archivedon-fetch.${{ matrix.target }}
                    cp target/${{ matrix.target }}/release/archivedon dest/archivedon.${{ matrix.target }}

            -   name: Release
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    files: |
                        ./dest/*
